# Use the official Nginx base image
FROM nginx:latest

# Copy custom nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Create a custom directory and set it as a working directory
WORKDIR /var/opt/nginx

# Expose port 80
EXPOSE 80